### PR TITLE
Change Md prefix to Mat in @angular/material >= beta.11

### PR DESCRIPTION
**Pull request by marlusantos**
In package.json is set to use "@angular/material": "^2.0.0-beta.11" [doc](https://github.com/angular/material2/releases/tag/2.0.0-beta.11) take a look issue about this [link](https://github.com/angular/material2/issues/7625)
Solution is change: MdButtonModule....Md* for MatButtonModule, MatCheckboxModule, MatInputModule, MatListModule, MatProgressBarModule.

This PR is just a fix, because I had problems.

### CODE REVIEW

**Comment by alexsicart** [comment]
@marlusantos it's not working in my computer. It doesn't display well te angular material elements

**Comment by alexsicart** [comment]
@marlusantos do you know how to make the actual webpage responsivness for mobile?

**Comment by marlusantos** [comment]
@alexsicart I need take a look. In fact I open the issue #35 to check your structure. When it was modularized some css broke I think.

For a responsive screen a good solution is to use bootstrap. I'm not a frontend expert but I can try.

**Comment by alexsicart** [comment]
@marlusantos I don't why, mat doesn't work for me, I'll take a look documentation. Thanks :)

**Pull request closed without merging**
